## This is the config file that determnines what analyses will
## be run on which sample subset from which parent BCF


#### DEFINITIONS SECTIONS #####

# every BCF file used here must correspond to the same
# reference genome and thus to the same scaffold groups file.
# These are identified here:
fai_path: .test/resources/genome.fasta.fai
scaff_group_path: .test/resources/scaffold_groups.tsv



# this is the short name and the path to the BCF file that will be used
# the key here (testy) corresponds to wildcard {bcf_id}.  The sample subsets
# should, of course, correspond to a particular
# bcf file, so they go here.  If there are meta data files for association
# studies in ANGSD, these go here as the dotsample.
bcf:
  testy:
    path: ".test/resources/100_fish.bcf"
    sample_subsets:
      all:
        path: .test/sample_subsets/all-fish.txt     #  all 100 fish
        dotsample: .test/data/dot-samples-all.tsv
      males:
        path: .test/sample_subsets/males.txt    # just the males
        dotsample: .test/data/dot-samples-males.tsv
      females:
        path: .test/sample_subsets/females.txt  # just the females
        dotsample: .test/data/dot-samples-females.tsv 


# same thing here, we can define different sets of bcftools filters
# that we might want to use, and we give them nicknames. The 
# nicknames/keys here correspond to wildcard 
bcftools_opts:
  snps05: -v snps -m 2 -M 2 -i 'FILTER="PASS" && MAF >= 0.05'


#### SETTING SECTIONS #####

pcangsd:
  url: git@github.com:eriqande/pcangsd.git
  version: 705ca4c19630ed9c2dd254b0bfd528b8ee25d5c0





#### PARAMETERS SECTION
# Here we can give some short names for different sets of parameters
# that we will use later for particular ultimate targets

# these are all the standard parameters in the file paths
main_params:
  TYPICAL_SET:
    bcf: testy
    filt: snps05
    sample_subset: all
    thin_spec: "0_0"
    maf: 0.05
    npc: 12 # this is just the number of pcs to attach to the dot-samples file


# Here we provide different sets of parameters for particular
# analyses.
params:
  do_asso:
    agephe_cohort_and_four_pcs_as_covariates:
      angsd_opts: " -doMaf 4 -doAsso 4 "
      whichPhe: " age "
      whichCov: " cohort,PC-1,PC-2,PC-3,PC-4 "



#### TARGETS SECTION

# here we can request targets that are the products of
# main_params and analyses from the params block above

# I have to figure out the best way to cycle over these and produce
# target files for.
targets:
  any_name:
    main: TYPICAL_SET
    analyses: 
      do_asso:
        agephe_cohort_and_four_pcs_as_covariates









